import streamlit as st
import sys
import os
import pandas as pd
import numpy as np

# Add parent directory to path to import from src
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.ui import load_css, page_header, top_navbar
from src.data_loader import load_data, engineer_features
from src.models import load_all_models
from src.viz import plot_feature_importance, plot_actual_vs_predicted, plot_confusion_matrix
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix

st.set_page_config(page_title="Model Insights", layout="wide")
load_css()
top_navbar("Model Insights")

page_header("Machine Learning Insights", "fa-solid fa-brain", "Deep dive into model performance and feature importances for GPA Prediction.")

@st.cache_data
def get_model_evaluation_data():
    df = load_data()
    df_eng = engineer_features(df)
    
    preprocessor, gpa_model, skill_model, burnout_model, le = load_all_models()
    
    num_cols = ["Pre_Semester_GPA", "Weekly_GenAI_Hours", "Tool_Diversity", "Traditional_Study_Hours", "Perceived_AI_Dependency", "Anxiety_Level_During_Exams"]
    ord_cols = ["Year_of_Study", "Prompt_Engineering_Skill"]
    nom_cols = ["Major_Category", "Primary_Use_Case", "Institutional_Policy"]
    bool_cols = ["Paid_Subscription"]
    
    # Transform data to get predictions
    X = df_eng[num_cols + ord_cols + nom_cols + bool_cols]
    y_true_gpa = df_eng["Post_Semester_GPA"]
    
    X_processed = preprocessor.transform(X)
    y_pred_gpa = gpa_model.predict(X_processed)
    
    # Get all feature names generated by the preprocessor
    raw_feature_names = preprocessor.get_feature_names_out()
    # Clean up prefixes like 'num__', 'nom__', 'ord__' added by ColumnTransformer
    all_feature_names = [name.split('__')[-1] for name in raw_feature_names]
    
    # Get feature importances
    importances = gpa_model.feature_importances_
    feat_imp_dict = dict(zip(all_feature_names, importances))
    
    # Filter top 15 features
    top_features = dict(sorted(feat_imp_dict.items(), key=lambda item: item[1], reverse=True)[:15])
    
    # Evaluate Burnout Model
    y_true_burnout = df_eng["Burnout_Risk_Level"]
    y_true_burnout_enc = le.transform(y_true_burnout)
    y_pred_burnout_enc = burnout_model.predict(X_processed)
    
    return y_true_gpa, y_pred_gpa, top_features, y_true_burnout_enc, y_pred_burnout_enc, le.classes_

with st.spinner("Analyzing XGBoost Model..."):
    try:
        y_true, y_pred, top_features, y_true_burnout_enc, y_pred_burnout_enc, labels = get_model_evaluation_data()
        
        st.markdown('<div class="animate__animated animate__fadeInUp">', unsafe_allow_html=True)
        col1, col2 = st.columns([1, 1])
        
        with col1:
            st.markdown('<div style="background: rgba(15, 32, 39, 0.4); padding: 20px; border-radius: 12px; backdrop-filter: blur(15px); border: 1px solid rgba(0, 210, 255, 0.2); box-shadow: 0 8px 32px rgba(0,0,0,0.3); height: 100%;">', unsafe_allow_html=True)
            st.markdown('<h3 style="margin-top:0; color:#00d2ff;"><i class="fa-solid fa-bullseye"></i> Actual vs Predicted GPA</h3>', unsafe_allow_html=True)
            st.markdown("Evaluating the XGBoost Regressor's accuracy on the dataset.")
            fig_scatter = plot_actual_vs_predicted(y_true, y_pred, "")
            st.plotly_chart(fig_scatter, use_container_width=True)
            
            # Simple metrics
            rmse = np.sqrt(((y_true - y_pred) ** 2).mean())
            st.info(f"**Root Mean Squared Error (RMSE):** {rmse:.3f}")
            st.markdown('</div>', unsafe_allow_html=True)
            
        with col2:
            st.markdown('<div style="background: rgba(15, 32, 39, 0.4); padding: 20px; border-radius: 12px; backdrop-filter: blur(15px); border: 1px solid rgba(0, 210, 255, 0.2); box-shadow: 0 8px 32px rgba(0,0,0,0.3); height: 100%;">', unsafe_allow_html=True)
            st.markdown('<h3 style="margin-top:0; color:#00d2ff;"><i class="fa-solid fa-list-ol"></i> Top Feature Importances</h3>', unsafe_allow_html=True)
            st.markdown("Which factors have the most weight in determining a student's Post-Semester GPA?")
            fig_imp = plot_feature_importance(top_features, "")
            st.plotly_chart(fig_imp, use_container_width=True)
            st.markdown('</div>', unsafe_allow_html=True)
            
        st.markdown('</div><br>', unsafe_allow_html=True)
        
        # --- NEW SECTION: CLASSIFIER EVALUATION ---
        st.markdown('<div class="animate__animated animate__fadeInUp animate__delay-1s">', unsafe_allow_html=True)
        st.markdown('<h2><i class="fa-solid fa-fire-flame-curved" style="color:#ff6600;"></i> Burnout Risk Classifier Performance</h2>', unsafe_allow_html=True)
        
        # Calculate Metrics
        acc = accuracy_score(y_true_burnout_enc, y_pred_burnout_enc)
        precision, recall, f1, _ = precision_recall_fscore_support(y_true_burnout_enc, y_pred_burnout_enc, average='weighted')
        cm = confusion_matrix(y_true_burnout_enc, y_pred_burnout_enc)
        
        # Metric Cards Row
        m1, m2, m3, m4 = st.columns(4)
        def metric_card(title, val, icon, color):
            return f'''
            <div style="background: rgba(15, 32, 39, 0.4); padding: 20px; border-radius: 12px; text-align: center; border: 1px solid rgba(0, 210, 255, 0.2); backdrop-filter: blur(10px);">
                <i class="{icon}" style="font-size: 2rem; color: {color}; margin-bottom: 10px;"></i>
                <h4 style="margin: 0; color: rgba(255,255,255,0.7);">{title}</h4>
                <h2 style="margin: 5px 0 0 0; color: {color};">{val:.2%}</h2>
            </div>
            '''
        
        with m1:
            st.markdown(metric_card("Accuracy", acc, "fa-solid fa-check-double", "#39ff14"), unsafe_allow_html=True)
        with m2:
            st.markdown(metric_card("Precision", precision, "fa-solid fa-crosshairs", "#00d2ff"), unsafe_allow_html=True)
        with m3:
            st.markdown(metric_card("Recall", recall, "fa-solid fa-reply-all", "#ffea00"), unsafe_allow_html=True)
        with m4:
            st.markdown(metric_card("F1-Score", f1, "fa-solid fa-balance-scale", "#ff007f"), unsafe_allow_html=True)
            
        st.markdown('<br>', unsafe_allow_html=True)
        
        # Confusion Matrix Chart
        st.markdown('<div style="background: rgba(15, 32, 39, 0.4); padding: 20px; border-radius: 12px; backdrop-filter: blur(15px); border: 1px solid rgba(0, 210, 255, 0.2);">', unsafe_allow_html=True)
        st.markdown('<h3 style="margin-top:0; color:#00d2ff;"><i class="fa-solid fa-border-all"></i> Confusion Matrix</h3>', unsafe_allow_html=True)
        fig_cm = plot_confusion_matrix(cm, labels)
        st.plotly_chart(fig_cm, use_container_width=True)
        st.markdown('</div>', unsafe_allow_html=True)
        st.markdown('</div><br>', unsafe_allow_html=True)
        # ------------------------------------------
        
        st.markdown('<div class="animate__animated animate__fadeInUp animate__delay-1s">', unsafe_allow_html=True)
        st.markdown("""
        <div style="background: rgba(15, 32, 39, 0.4); padding: 30px; border-radius: 12px; backdrop-filter: blur(15px); border: 1px solid rgba(0, 210, 255, 0.3); box-shadow: 0 8px 32px rgba(0,0,0,0.4);">
            <h3 style="margin-top:0; color: #00d2ff;"><i class="fa-solid fa-microscope"></i> Model Interpretation</h3>
            <ul style="color: rgba(255,255,255,0.9); font-size: 1.15rem; line-height: 1.8;">
                <li><strong>Pre-Semester GPA</strong> is consistently the strongest predictor of Post-Semester GPA, which aligns with educational baselines.</li>
                <li><strong>Traditional Study Hours</strong> and <strong>Anxiety Levels</strong> follow closely, proving that core academic habits remain vital regardless of AI usage.</li>
                <li>Among AI-specific features, <strong>Perceived AI Dependency</strong> and <strong>Prompt Engineering Skill</strong> play a significant role in variance, highlighting that <em>how</em> a student uses AI matters more than just the hours spent.</li>
            </ul>
        </div>
        """, unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)
        
    except Exception as e:
        st.error(f"Error evaluating model: {e}")
